CREATE DATABASE IF NOT EXISTS db_mysql;

USE db_mysql;

CREATE TABLE IF NOT EXISTS `list` (
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `task` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
    PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=7;
